### ISSUE TITLE
White screen shown in the first boot

### ISSUE THREAD

**Issue by suwahime** [wtetsu/mouse-dictionary#19]
Steps to Reproduce

1. Install Chrome (ver. 72.0.3626.109 Official Build 64bit)  into MacOSX 10.14.3 .
2. Install Mouse Dictionary (ver. 1.1.9) from Chrome Web Store.
3. Click extension icon of Mouse Dictionary, and open the popup window.
4. Point any English term.

Expected Result

- Shown translated sentence of English term in the popup window.

Actual Result

- White screen shown in the popup window.

Suggestion

- Add how to installation (ex. "Open option menu on the first boot.") in the store page.
- Or, add description (ex. "Not initialized. Please open option menu.") in the not initialized popup window.

----

再現手順

1. MacOSX 10.14.3 に、Chromeのバージョン：72.0.3626.109（Official Build）（64 ビット）をインストールする
2. chromeウェブストアから Mouse Dictionary （バージョン：1.1.9） を拡張機能としてインストールする
3. 拡張機能一覧から Mouse Dictionary のアイコンをクリックして、ポップアップウィンドウを立ち上げる
4. ポップアップウィンドウが立ち上がった状態でウェブページ内の任意の英単語にマウスカーソルを合わせる

期待する結果

- Mouse Dictionary のポップアップウィンドウに、翻訳結果が表示される

実際の結果

- ポップアップウィンドウ内は白紙のまま、何も表示されない

提案

- 最初にオプションメニューを開くことが必須ということを、ストアページの説明文に記載してはどうでしょうか
- もしくは、辞書情報が登録されていないのでオプションメニューを開かなければならない旨を、ポップアップウィンドウに表示してはどうでしょうか

**Comment by wtetsu** [comment]
Thank you for your suggestion!
Sounds like a good idea so I'll deal with it. First I assumed users know Mouse Dictionary from my Qiita article, but now I think I should take care of users that know this tool on Chrome Web Store and so on.

**Comment by wtetsu** [comment]
![image](https://user-images.githubusercontent.com/515948/53409063-637d9c00-3a03-11e9-9b08-8312533c2b4d.png)
![image](https://user-images.githubusercontent.com/515948/53409078-6d070400-3a03-11e9-993b-c76acba0b109.png)

**Comment by wtetsu** [comment]
v1.2.0
