### ISSUE TITLE
Chromium 76.0.3775.0で設定画面がエラーになる

### ISSUE THREAD

**Issue by array** [wtetsu/mouse-dictionary#22]
Chromium 76.0.3775.0を使っているChrome, Vivaldiで設定画面を開こうとすると
”Uncaught TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Index property setter is not supported.”
とエラーメッセージがでて設定画面が出ません。
Firefoxでは問題ないです。
Mouse Dictionary 1.2.4　です。

**Comment by wtetsu** [comment]
ご報告ありがとうございます。

たぶん、これに起因しています。
https://github.com/facebook/react/issues/15375

**Comment by wtetsu** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=951046

> This is working as intended following web standards.
> We apologize that we had supported a wrong behavior for a long time, but we fixed it.  Please kindly fix the affected web sites and JS frameworks.

**Comment by wtetsu** [comment]
@array v1.2.5で修正したのでご確認ください
