### ISSUE TITLE
文字列置換結果が閲覧ページに影響を受ける

### ISSUE THREAD

**Issue by PrsPrsBK** [wtetsu/mouse-dictionary#23]
Chrome版の文字列置換ルールの適用結果が、閲覧中のウェブページのスタイルによる影響を受けるかもしれません。

今のところTypeScript公式のドキュメントで `<span>` 適用でフォントサイズが大きくなる現象を確認したのみです。Firefox版では発生しません。

単に表示ウィンドウを大きくすれば用は足りますが、閲覧ページから影響を受けるのは(受けるとすれば、ですが)おそらく望まれない動作であると考え、報告します。

## 環境

* ブラウザ: Google Chrome(74.0.3729.131（Official Build） （64 ビット）)
  (MS Edge Canary Version 76.0.155.0 (Official build) canary (64-bit) も同様でした)
* OS: Microsoft Windows [Version 10.0.17763.475]

## スクリーンショット
以下のスクリーンショットはTypeScript公式のドキュメントを開いて "Type" にマウスカーソルをホバーさせたものです。

[Basic Types · TypeScript](https://www.typescriptlang.org/docs/handbook/basic-types.html)

初期設定: 一番下の '(doing)' が一段大きくなります。

![2019-05-13_02Chrome](https://user-images.githubusercontent.com/24764443/57621613-dfc95980-75c6-11e9-91bd-fee109f2fef7.png)

文字列置換ルールの `(\(.+?\))` に `<span>`の入れ子を追加した場合: 括弧の部分が一段階大きくなります。

```
<span><span style="color:#008000;">$1</span></span>
```
![2019-05-13_03ChromeNest](https://user-images.githubusercontent.com/24764443/57621636-ece64880-75c6-11e9-860c-738decbcd789.png)

Firefox(Developer Edition, 67.0b19)(アドオン初期設定)

![2019-05-13_01Firefox](https://user-images.githubusercontent.com/24764443/57621657-f7084700-75c6-11e9-9888-59beec2a7202.png)

**Comment by wtetsu** [comment]
ご報告ありがとうございます。

実はMouse Dictionaryの表示は本体サイトのスタイルにけっこう影響を受けるのですが、こんなにおかしくなっているのは初めて見ました。

そのサイトのspanのfont-sizeが1.6emとかになっているのが原因なので、応急処置としては、文字列置換ルール設定の、

```html
<span style="color:#008000;">$1</span>
```

を、

```html
<span style="color:#008000;font-size:1.0em;">$1</span>
```

とかに変えれば回避できます。


根本対応策は、そのうち考えます。

**Comment by wtetsu** [comment]
@PrsPrsBK 

ご報告ありがとうございます。

実はMouse Dictionaryの表示は本体サイトのスタイルにけっこう影響を受けるのですが、こんなにおかしくなっているのは初めて見ました。

そのサイトのspanのfont-sizeが1.6emとかになっているのが原因なので、応急処置としては、文字列置換ルール設定の、

```html
<span style="color:#008000;">$1</span>
```

を、

```html
<span style="color:#008000;font-size:1.0em;">$1</span>
```

とかに変えれば回避できます。


根本対応策は、そのうち考えます。

**Comment by PrsPrsBK** [comment]
> 実はMouse Dictionaryの表示は本体サイトのスタイルにけっこう影響を受けるのですが

そうなのですね。これまで一定の表示しか見たことがなく、影響を受けないようになっているのかなと思っていました。

回避方法もありがとうございます。セットしたら見やすくなりました。

**Comment by wtetsu** [comment]
default view(v1.2.7)

![image](https://user-images.githubusercontent.com/515948/59601087-f7ec4580-913d-11e9-86b4-fe03c2b66aab.png)

**Comment by wtetsu** [comment]
Fixed in v1.2.7
