### ISSUE TITLE
/main/entry/en.js の関数 createLookupWordsEn() が正常に動作していない

### ISSUE THREAD

**Issue by koba-ninkigumi** [wtetsu/mouse-dictionary#27]
"lilies"にマウスをあてても"lily"が検索されません。

具体的には、 /main/entry/en.js の createLookupWordsEn() 関数が正常に動作していないため、
createLookupWordsEn("lilies")の返り値に"lily"が含まれていないことが原因です。
（ただし、 /main/rules.js までは正常に動作しているため、 rule.doBase("lilies")の返り値には"lily"が含まれています。）

同様に、 /main/rules.js の rule.doPronoun(["my"]) は、"one's"を返しますが、
/main/entry/en.js の createLookupWordsEn("my") には不都合があるため、"my"にマウスをあてても"one's"を返さないようです。

**Comment by wtetsu** [comment]
@koba-ninkigumi 

私が確認したところ、公開している最新版のv1.2.8でも、現時点でのmaster(775cbf3cd323ad0bf5792041a05152c1ada1d379)でも、lillyを引けるようです。

ご利用のバージョンをお教えいただけますでしょうか。


----

![image](https://user-images.githubusercontent.com/515948/62945360-8e28a900-be19-11e9-9ecb-4f491708e8df.png)

**Comment by wtetsu** [comment]
my -> one'sの挙動

この変換は、辞書データの見出しとしては、たとえばですが"on my own"ではなく"on one's own"と記載されている(ことがある)ことに対応する挙動です。一方でmy単体にカーソルを当ててone'sが表示さないのは、意図的な挙動となっています(表示されても特に嬉しくないと思うので)
もしこの挙動で困る状況などありましたらご指摘ください。

**Comment by koba-ninkigumi** [comment]
すばやいお返事ありがとうございます。

chrome://extensionsで確認したところ、バージョン1.2.8でした。が、一度、mouse-dictionaryを削除して再度インストールし直したところ、こちらでも"lilies"で"lily"が表示されました。お騒がせしてすみません。
初期状態から変更したことといえば、辞書登録したことと、設定内で文字列置換ルールを10個程度登録していたぐらいだったのですが、、、。

そして、先ほどまでは、/main/lookuper.jsのentry.build()の返り値に"lily"が含まれていなかったのですが、これもきちんと含まれていることを確認しました。

my -> one'sの挙動については理解いたしました。

こちらのほうはCloseさせていただきます。
