### ISSUE TITLE
Some Japanese transforming doesn't work correctly(e.g. 愛します -> 愛する)

### ISSUE THREAD

**Issue by koba-ninkigumi** [wtetsu/mouse-dictionary#28]
"愛します"にマウスをあてても"愛する"が検索されません。

具体的には、/main/lookuper.js の関数 entry.build("愛します")の返り値に"愛する"が含まれていないことが原因です。
なお、createLookupWordsJa("します")の返り値には"する"が含まれるので、サ変動詞の活用処理自体が考慮されていないわけではなさそうです。

**Comment by wtetsu** [comment]
ご報告ありがとうございます。
内部的には別ライブラリの処理なので、↓にIssueをつくりました。
wtetsu/deinja#2

**Comment by wtetsu** [comment]
Before:
![image](https://user-images.githubusercontent.com/515948/63259024-4e017480-c2b8-11e9-95b9-5ae2cf6e6ce9.png)

After:
![image](https://user-images.githubusercontent.com/515948/63258986-3aeea480-c2b8-11e9-8e11-101adcac79e2.png)

**Comment by wtetsu** [comment]
* 愛させる
* 愛さない
* 愛される
* 愛しそう
* 愛したい
* 愛したら
* 愛したり
* 愛します

**Comment by wtetsu** [comment]
fixed in v1.3.1
