### ISSUE TITLE
複数形への対応

### ISSUE THREAD

**Issue by xXkiluxkiluXx** [wtetsu/mouse-dictionary#29]
普段からMouse dictionaryを使用しており、複数形になった時に表示していただけると嬉しいです。
sとかesとかで複雑な処理が絡むかもしれませんが、できればでいいので実現していただけるとありがたいですｍ（・。・）ｍ

**Comment by wtetsu** [comment]
@xXkiluxkiluXx 

表示できないのはどのような状況でしょうか?
すでに、不規則なものも含めて表示しているはずなのですが。

boys, cities, houses, stones

alumni, feet, knives, mice, women

**Comment by wtetsu** [comment]
![image](https://user-images.githubusercontent.com/515948/64924573-32d74580-d821-11e9-9086-ad67bad79fa1.png)

**Comment by xXkiluxkiluXx** [comment]
私の語学力が低くて申し訳ございません。
所有格でした。
BBCなどで英語の勉強をしていると名詞'sとかのsがつく単語で、出たりでなかったりする単語があります

**Comment by wtetsu** [comment]
出ない語の具体例を挙げていただないでしょうか。

**Comment by xXkiluxkiluXx** [comment]
star's Ken's winner'sなどで出ませんでした

**Comment by wtetsu** [comment]
* どのような動作を期待して
* 実際はどう期待と異なるか

を明示していただかないと、どうにもできないです。

私の手元ではstar'sにカーソルを合わせるとstarの意味が出て、
これはも、少なくとも私の期待は動作は一致しています。

![image](https://user-images.githubusercontent.com/515948/65145156-d0b25680-da53-11e9-8655-6344a47e0c09.png)

**Comment by wtetsu** [comment]
大前提として、バージョンは最新にしてください(現在は1.3.1)

**Comment by xXkiluxkiluXx** [comment]
バージョンをlatestにしたところ治りました
お手を煩わせて申し訳ございません
