### ISSUE TITLE
句動詞(e.g. fan out)の意味の表示

### ISSUE THREAD

**Issue by sthtnr** [wtetsu/mouse-dictionary#30]
こんにちは。素晴らしい拡張機能を開発していただきありがとうございます。
いつも使わせてもらっています。

例えばですが、「fanout」という単語にカーソルを合わせた時と、「fan out」という２つの単語の組み合わせにカーソルを合わせた時に表示されるものが異なります。
 
<img width="622" alt="スクリーンショット 2019-11-04 19 38 50" src="https://user-images.githubusercontent.com/45104858/68115066-dc41da00-ff3a-11e9-90a9-0e15f283ebca.png">

<img width="621" alt="スクリーンショット 2019-11-04 19 39 14" src="https://user-images.githubusercontent.com/45104858/68115073-dfd56100-ff3a-11e9-85ed-c065fa00549b.png">

そこで、「fanout」にカーソルを当てた時に「fan out」にカーソルを当てた時の意味を表示できるようにすることは可能でしょうか？

今回は「fanout」という句動詞について言及しましたが、他の句動詞でも度々同じ現象(「hogefuga」にカーソルを当てても句動詞「hoge fuga」の意味は表示されないが、
「hoge fuga」にカーソルを当てるとその句動詞の意味が表示される)が起こっています。

【使用している辞書データ】 EIJIRO text data
【拡張機能version】 1.3.1

**Comment by wtetsu** [comment]
あったら便利な気がする、かつ速度を落とさず実装する方法がある気がするので、検討してみます。

**Comment by wtetsu** [comment]
fanout

**Comment by sthtnr** [comment]
対応していただきありがとうございます。
次バージョンのリリースに期待しています 👀

**Comment by wtetsu** [comment]
@sthtnr 

v1.3.2 で対応してみたのでお試しください。
簡単な句動詞なら検知できますが、完璧ではありません。
こういうケースで期待通り動かない、などありましたらご提示ください。
