### ISSUE TITLE
Touching resizing grip results in turning off  selectable mode

### ISSUE THREAD

**Issue by shohei-sakamoto** [wtetsu/mouse-dictionary#31]
日々、便利に使っています。ありがとうございます。

resize/draggable機能のことなのですが、リサイズの方が画面内のテキストをドラッグする時に干渉してしまいます。また、画面を動かしたくない時に動かしてしまうことがあります。
この機能を無効にするオプションを作って頂けたら嬉しいです。

よろしくお願いします。

**Comment by wtetsu** [comment]
「干渉する」というのは、どのような具体的にはどのようなことが発生するのでしょうか?

なお、表示・非表示を切り替える押しやすいショートカットキーを設定して、必要のないときは非表示にするのが、Mouse Dictionaryとして推奨する使い方です。

**Comment by shohei-sakamoto** [comment]
[画面収録 2019-12-09 1.58.59.zip](https://github.com/wtetsu/mouse-dictionary/files/3936642/2019-12-09.1.58.59.zip)

マウスポインタがリサイズのアイコンに変化し、ドラッグすることができなくなります。
ドラッグできないこともないのですが、Readlangなどで単語帳を作る場合に煩わしさがあります。
また、マウスポインタがリサイズのアイコンに変わる範囲も左右で異なっています。

Readlangと併用すると語学学習が非常に捗り、重宝しています。
この様なアドオンを作って頂き、とても感謝しております。

**Comment by wtetsu** [comment]
> Readlangと併用すると語学学習が非常に捗り、重宝しています。この様なアドオンを作って頂き、とても感謝しております

ありがとうございます:smile:

----

ご報告いただいた現象についてですが、基本的方針として、特定の現象に対応するためだけのオプションは追加したくないと考えています。個別の事象や要望に対応するためのオプションを都度追加しているときりがないし、そのようなことをしていると設定や内部処理もどんどん複雑化して使いづらくなったり、バグの温床になるためです。

リサイズや移動はMouse Dictionaryとしてはかなり基本的な機能で、これを無効化するような使い方は推奨していません。

----

で、報告いただいた挙動を見ると、(Mouse Dictionary自体の不具合化どうかは不明ですが)明らかにおかしくなっているので、このような状態にならないようにすることがまず最初に考えたいところになります。

とりあえず初期設定に戻してみていただけますか。
https://github.com/wtetsu/mouse-dictionary/wiki/Factory-reset

それでもこの事象が発生するようでしたら、以下について教えて下さい。

* この現象はreadlangだけで発生するのでしょうか、あるいは他でも発生するのでしょうか
* この現象は常に発生しているのでしょうか。それとも特定の操作やタイミングで発生するのでしょうか
* 発生するサイトと発生させる手順を教えて下さい

**Comment by shohei-sakamoto** [comment]
ご返信ありがとうございます🙏
無理を言ってしまい、すみません。
オプションの件、承知いたしました。

質問にお答えします。

・この現象はreadlangだけで発生するのでしょうか、あるいは他でも発生するのでしょうか

Readlang以外のサイトでも発生します。

・この現象は常に発生しているのでしょうか。それとも特定の操作やタイミングで発生するのでしょうか

常に発生しています。

発生するサイトと発生させる手順を教えて下さい

どのようなサイトでも発生し、初期設定でも発生します。


[画面収録 2019-12-10 6.36.31.zip](https://github.com/wtetsu/mouse-dictionary/files/3941844/2019-12-10.6.36.31.zip)

文頭からドラッグする為に、Mouse Dictionaryウィンドウ全体のpaddingをpadding: 32px 34px 32px 34px;に変更しておりました。
初期設定に戻すと、マウスポインタがresizeのアイコンに変わる範囲が右側で狭くなりました。しかし、左側に比べるとまだ広い様に感じます...。
さらに、文頭からドラッグすることができなくなります。

よろしくお願いします🙇‍♂️

**Comment by wtetsu** [comment]
いただいた動画で、やろうとしていることと、それを阻害している現在の挙動を理解しました。

つまり、ダブルクリックして「選択モード」にした後に、小窓の左端からテキストを範囲選択したいにも関わらず、小窓の縁にカーソルが差し掛かるとリサイズ可能判定がなされて「選択モード」が解除されてしまう、ということでしょうか。

この挙動で嬉しい人はあまりいないと思うので、オプションの追加とかでなしにも根本的に修正しようと思います。

次バージョン(v1.3.4)で変更される予定です。

**Comment by wtetsu** [comment]
@shohei-sakamoto 
さきほどv1.3.4がリリースされてようなので、ご確認ください。

**Comment by shohei-sakamoto** [comment]
ずっと使い易くなりました！

ありがとうございます😃

**Comment by wtetsu** [comment]
😄
