### ISSUE TITLE
First time guide is incorrect for Firefox

### ISSUE THREAD

**Issue by piroor** [wtetsu/mouse-dictionary#32]
初回使用時に辞書が未設定だと、ページ内に開いたポップアップの中に `初めに辞書データをロードしてください(拡張のアイコンを右クリック→「オプション」)` という案内のメッセージが表示されます。
しかしながら、Firefoxにはこのメニュー項目がありません。実際には、

 * アイコンを右クリック→「拡張機能を管理」を選択→「...」をクリック→「オプション」を選択

とする必要があります。

初回使用時に戸惑ったため、メッセージを各実行環境向けに変えることが望ましいと思われます。

**Comment by wtetsu** [comment]
#33 でメッセージとしては対応していただきましたが、このIssueはリリースするまで残しておきます。

**Comment by wtetsu** [comment]
v1.3.6

https://addons.mozilla.org/ja/firefox/addon/mousedictionary/

![image](https://user-images.githubusercontent.com/515948/73606921-0b77ee00-45f3-11ea-80d4-e110087f7a81.png)
