### ISSUE TITLE
Firefox version doesn't invoke

### ISSUE THREAD

**Issue by piroor** [wtetsu/mouse-dictionary#34]
#33 の検証中に気が付いたのですが、少なくとも初期設定がなされていない状況においてこちらの拡張機能が全く動作しない（初回起動時のメッセージも表示されない）様子でした。

## 再現手順

1. `git clone https://github.com/wtetsu/mouse-dictionary.git`
2. ` cd mouse-dictionary`
3. `npm install`
4. `npm run build-firefox`
5. Firefoxを新規プロファイルで起動
6. `about:debugging`を開く
7. mouse-dictionary/dist-firefox/manifest.json を選択
8. Webページを開いた状態でツールバー上のMouse Dictionaryボタンをクリック

## 期待される結果

初期設定を促すメッセージが表示される。

## 実際の結果

`settings is undefined`というアラートが表示される。
エラーコンソール上のエラーメッセージ：

```
TypeError: "settings is undefined"
    createDialogElement view.js:14
    create view.js:30
    initialize main.js:71
    processFirstLaunch main.js:38
```

## 環境

* Firefox 72.0.1
* Mouse Dictionary 3630aefe5240942667d56912d9c4aca3ae14216c

**Comment by piroor** [comment]
エラーを元に辿ってみたところ、 `env.disableUserSettings = true;` と設定されていることが直接の原因である模様でした。

**Comment by wtetsu** [comment]
ありがとうございます。

実はFirefox版はいろいろな事情で継続して更新する気はあまりなくなっているので、本件の根本解決ができるかどうかはわかりませんが、#33の件は対応すると思います。

その場合はFirefox版の最新である [v1.2.8](https://github.com/wtetsu/mouse-dictionary/releases/tag/v1.2.8) から派生する形になります。

**Comment by piroor** [comment]
> 実はFirefox版はいろいろな事情で継続して更新する気はあまりなくなっているので、

なんと、そうでしたか……
状況を追えていないため、継続的な更新が望めないということを把握できておりませんでした。
余力があればmasterを一通りFirefoxで動く状態にまで持っていくようPRをいくつか出したいと考えていたのですが、仮にそれができたとしても、今後のご対応は難しい感じでしょうか？

**Comment by wtetsu** [comment]
ご協力いただく分には大変ありがたいです！
もちろん、最新でFirefoxで動くことが確認できたら、リリースすることは可能です。

ただ、確か v1.2.8~v1.3.1 で起動を速くするためにけっこう変更が入っており、その辺の仕組みがFirefoxと相容れるものなのか確認していないので、もしその辺が動かなかった場合はなかなか骨の折れる作業になる可能性があります。
(といっても、すんなり動けば問題ないですが)

----

大きな変更の具体例としては、[この辺](https://github.com/wtetsu/mouse-dictionary/tree/master/rule)のruleファイルというものがビルド時にdata/rule.jsonという一つのファイルになり、これが[rule.js](https://github.com/wtetsu/mouse-dictionary/blob/master/src/main/rule.js)から起動時に読み込まれる仕組みになりました。
(同等のデータは、もともとは.js内に定義されていた)


このようにした理由は、

* [JSONのパースはjsより速い](https://v8.dev/blog/cost-of-javascript-2019)
* JSONの読み込み・評価を非同期処理にして、表示処理を続ける

といったもので、ウィンドウ表示までの時間を少しでも短くしようという意図がありました(ロジックと設定を分離するという意図もあります)

**Comment by wtetsu** [comment]
#35 を反映後のビルドを Firefox 72.0.1で試したところ、おおまかには問題なく動くようですね。細かい問題はあるかもしれませんが。

(ひとつ前よりコメントの件は、以前試したところうまく動かなかったと記憶しているので、詳しく書いたのですが)

この感じなら少しの労力で修正できそうな気がしています。

**Comment by wtetsu** [comment]
v1.3.6

https://addons.mozilla.org/ja/firefox/addon/mousedictionary/
