### ISSUE TITLE
PDF reader issue

### ISSUE THREAD

**Issue by shatano-htn** [wtetsu/mouse-dictionary#46]
Hi! I downloaded mouse-dictionary and tried to use on pdf. 
I opened my Pdf file from mozilla.github but seems like the dictionary won't show any word even i point out words with mouse.
Hope there is a way to fix it! Thanks a lot for creating this amazing tool!

<img width="992" alt="スクリーンショット 2020-09-06 午後10 07 15" src="https://user-images.githubusercontent.com/70841525/92323505-73148100-f08d-11ea-8dc0-42c9628eb5af.png">

**Comment by wtetsu** [comment]
@shatano-htn 
Hi, thank you for your repon.

Could you share the PDF file?

My Mouse Dictionart + PDF files works well.

**Comment by shatano-htn** [comment]
Thanks for the reply!
Please find the pdf below. 

https://classroom.upeace.org/elearning/pluginfile.php/14437/course/section/2151/Ramsbotham%202016%20Contemporary%20Conflict%20Resolution%20Ch%202%20pp%2038-67.pdf

**Comment by wtetsu** [comment]
I cannot log in.

![image](https://user-images.githubusercontent.com/515948/92325594-faaac180-f086-11ea-8fb8-ae06b5b69a16.png)

And, if your Mouse Dictionart works on other PDF files but doesn't work on one the specific PDF file, it's likely to be due to the file itself.

**Comment by shatano-htn** [comment]
I am sorry that I have sent you the URL which you cannot log in. 
Please find the attached document.

Yes I can use Mouse-dictionary for other PDF files. 
I am so amazed of this tool, will be so helpful  to use with my studying! 
[Ramsbotham 2016 Contemporary Conflict Resolution Ch 2 pp 38-67-圧縮済み.pdf](https://github.com/wtetsu/mouse-dictionary/files/5180243/Ramsbotham.2016.Contemporary.Conflict.Resolution.Ch.2.pp.38-67-.pdf)

**Comment by wtetsu** [comment]
> I am so amazed of this tool, will be so helpful to use with my studying!

Thank you for your feedback!

I've check the PDF file and I found it had no text data.
Probably, this PDF file was created by just scanning paper,
so virtually this is just an image file that has no text information.

In this case, it's impossible to use Mouse Dictionary on it.
You have to find or make text data first.

**Comment by shatano-htn** [comment]
Thank you for checking the PDF file and responded me promptly. 
Ok I got it. I will probably try to convert it to text data then will use the Mouse Dictionary.

Thanks again for your support!
Looking forward to seeing more updates in near future:)
