### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by baotapsamac** [wtetsu/mouse-dictionary#48]
Please help me.
When i tried to compile the code, I met error like this. How can I fix it.  Thanks
![image](https://user-images.githubusercontent.com/23546566/95719622-4b22c980-0c9a-11eb-8e44-7ae736f5dd10.png)
![image](https://user-images.githubusercontent.com/23546566/95719688-62fa4d80-0c9a-11eb-8ddd-b051b53ce203.png)

**Comment by wtetsu** [comment]
Hi, did you follow "How to develop"?
You need to build Mouse Dictionary using npm before make Chrome load it.

https://github.com/wtetsu/mouse-dictionary#how-to-develop

**Comment by baotapsamac** [comment]
Thanks. I did it.

**Comment by wtetsu** [comment]
Did you load dist-chrome directory? (not src directory)
