### ISSUE TITLE
To scroll downward

### ISSUE THREAD

**Issue by GororiK** [wtetsu/mouse-dictionary#54]
Dear,
I'm enjoying this splendid application!
However, I cannot scroll downward in the window of mouse-dictionary.
This is why I cannot view all of the contents for the word I look up.
I'd appreciate if you tell me how to do it.

**Comment by wtetsu** [comment]
Hi, I think the easiest way is select words and use mouse to scroll.

![md-scroll2](https://user-images.githubusercontent.com/515948/103517089-f071c600-4eb4-11eb-807d-f28d5233f1eb.gif)

**Comment by GororiK** [comment]
Thank you.
I understand that I have to highlight the words before scrolling.
I really appreciate it.

Kazuya

**Comment by GororiK** [comment]
Hi,

I tried that action as below, but it was impossible to scroll down when I highlighted the words in Google document on Chrome.
Doesn’t the specification allow for that action?

Goto

**Comment by wtetsu** [comment]
I think it’s due to Google Document that is not very normal HTML document.

If you want to have it fixed, please create an issue or change this issue’s title or fix by your self. 
(Note that I cannot assure when I can deal with it)

**Comment by GororiK** [comment]
Thank you for the reply.
Sure. I’ll create a new issue about it.
I really appreciate it.

Goto

**Comment by wtetsu** [comment]
I write this document for new users.
https://github.com/wtetsu/mouse-dictionary/wiki/Window-manipulation
