### ISSUE TITLE
hard to see the icon of mouse-dictionary in the dark mode.

### ISSUE THREAD

**Issue by externvoid** [wtetsu/mouse-dictionary#57]
As the icon is black-ish, it should be brighter and more prominent on the chrome-extension panel at the upper-right of the browser.

**Comment by wtetsu** [comment]
I want to confirm the purpose of your request first.

* want to Improve UI?
* Just look and feel?

About the former.
For normal and usual usage, you don't have to look and push the icon.
Please set your keyboard shortcut.
https://github.com/wtetsu/mouse-dictionary/wiki/Advanced-features


About the latter.
It could be better so I'll think about it, but I think there is no perfect solution.
(If the icon was blue-ish but the browser's theme was blue-ish as well, it could be hard to see)

**Comment by externvoid** [comment]
The request is related to the UI.
The keyboard shortcut feature of the browser tends to raise a conflict issue of key binding. 
Pushing the icon is useful because the browsing is well suited to a mouse devise or trackpad. Moreover the name of this app is "Mouse-dictionary".

As you indicated earlier, no perfect solution, but the black-ish icon might be lack of visibility.

**Comment by wtetsu** [comment]
I don't think there is a conflict issue because you can set a Mouse Dictionary keyboard shortcut as you like, but the next version may have better icon visibility.

**Comment by wtetsu** [comment]
Left: current
Right: new


## Original theme

![image](https://user-images.githubusercontent.com/515948/107138949-1c241800-695b-11eb-8b87-88db46c20f8d.png)

## Dark theme

![image](https://user-images.githubusercontent.com/515948/107138951-22b28f80-695b-11eb-917c-5100db680bd9.png)

**Comment by externvoid** [comment]
Dark theme icon being planed looks nice and can be expected. Thanks a lot.
