### ISSUE TITLE
Chromeで使えません。

### ISSUE THREAD

**Issue by Kentaro97** [wtetsu/mouse-dictionary#60]
Chromeの拡張機能を追加しましたが、ポップアップしません。どうすればよいでしょうか？

Windws10 homeの最新バージョンを使っています。

Chromeも最新です。バージョン: 90.0.4430.93（Official Build） （64 ビット）

英辞郎のテキストデータも購入し、設定は問題なくできます。

拡張機能もOnにしています。

**Comment by wtetsu** [comment]
マニュアルをお読みください。

https://github.com/wtetsu/mouse-dictionary/wiki

https://qiita.com/wtetsu/items/c43232c6c44918e977c9
