### ISSUE TITLE
Why on earth does mouse dictionary work on Google docs one day but another day doesn't?

### ISSUE THREAD

**Issue by Kein-0809** [wtetsu/mouse-dictionary#66]
いつも便利に使わせていただいております．
毎日学校の課題のために、Google Docs上でMouse dictionaryを使わせていただいているのですが、Mouse dictionaryの機能が日によってマウスを英語にhoverした際に、反応したり、しなかったりします．
このことは、なぜ起こるのでしょうか？　また、改善点があったら教えていただきたいです．

![Waterfall model - Structured Methodology](https://user-images.githubusercontent.com/65139270/149539084-bc1448ef-7a62-4290-bffb-f595f8dbbeb4.jpeg)

**Comment by wtetsu** [comment]
https://twitter.com/wtetsu/status/1465263822688509959?s=20

どうも去年の後半あたりのGoogle Docs側の更新により、拡張からコンテンツにアクセスできなくなったようで、解決策は見つかっていません。

※もしGoogle Docs上で動作する他の辞書系ツールがあれば、その動きを参考にしてMouse Dictionaryにも改良を入れられそうですが、そのようなツールも見つかっていません(Google DictionaryやDeepLあたりも動きません)

Mouse Dictionaryが動いていた頃の古いドキュメントをコピーしてそれをもとにドキュメントを作成すればMouse Dictionaryが動いたままにできる、という情報が寄せられたことはありますが、私は未確認です。

なので、現在のところは、Google DocsではないMouse Dictionaryが動くドキュメントツールを使う、というのが代替策になります。

例:
* Web版のMicrosoft Office
* Notion
* Evernote ([Mouse Dictionary iframe support](https://chrome.google.com/webstore/detail/mouse-dictionary-iframe-s/nigglogmamjbcnljijokibobpcfgmdfn)のインストールも必要)

**Comment by Kein-0809** [comment]
そうだったんですね。
返信ありがとうございました。
わざわざ追加情報まで教えていただきありがとうございます。

**Comment by Kein-0809** [comment]
そうだったんですね。
返信ありがとうございました。
わざわざ追加情報まで教えていただきありがとうございます。

**Comment by wtetsu** [comment]
現在見つかっている回避策:
URLの最後に?mode=htmlを付与すると動くようになる模様です @Kein-0809 

~/edit
↓
~/edit?mode=html

**Comment by Kein-0809** [comment]
@wtetsu様 わざわざ解決策をご教示していただきありがとうございます
実際に試したところ、しっかり文字がマウスをホバーした際に反応しました。
これで課題がはかどります。ありがとうございます。

**Comment by wtetsu** [comment]
メモ: 2022年3月あたりに、`mode=html`は使えなくなってしまった模様。
