### ISSUE TITLE
Doesn't work properly on a webpage (calibre-web) 

### ISSUE THREAD

**Issue by yuis-ice** [wtetsu/mouse-dictionary#67]
I tried to use mouse-dictionary on [calibre-web](https://github.com/janeczku/calibre-web), a web-based self hosted app for Calibre, an EPUB reading software. But somehow it doesn't work well, like the screenshots below. 

Doesn't work on the book content: 

<img src="https://user-images.githubusercontent.com/24733624/152516202-5adc8eed-debb-4f7e-9431-9f996e644bfd.png" width="600" />

while works on the left menu bar: 

<img src="https://user-images.githubusercontent.com/24733624/152516187-eef9a94e-d0a2-4f12-815d-7d73aa1975c9.png" width="600" />

I assume this may be a z-index related issue or something but not sure. (do you have any sites that doesn't work well like this case?) 

Here the below is the reproduction steps, it's a little long way tho, I'd appreciate your help. 

## Reproduction: 

1. Install the Calibre software on Windows: [calibre - E-book management](https://calibre-ebook.com/)

2. Install a sample EPUB ebook, for instance: [The Complete Works of William Shakespeare by William Shakespeare - Free Ebook](https://www.gutenberg.org/ebooks/100)

3. Load the downloaded epub file on the software interface 

4. Install [calibre-web](https://github.com/janeczku/calibre-web), as the following steps

```
C:\Python37\python.exe -m virtualenv venv # I used python 3.7 but 3.5+ should work
. venv/Scripts/activate
pip install calibreweb
cps # this launches the server silently (note that no logs) 
```

5. Test 

Go to http://localhost:8083/ then find the book, open it, test if the extension works on your environment.

**Comment by wtetsu** [comment]
I think it's not due to z-index, but iframe that covers most of the content.
This iframe makes extensions (including Google Dictionary) hard to access its text contents.
I don't know how to work around it, but if you found dictionary-like extensions which are available on the content, let me know.
Perhaps I can improve Mouse Dictionary by looking into the extension's behavior.

![image](https://user-images.githubusercontent.com/515948/152532176-54a73ce6-6115-4aa4-812e-2f2be8fd011a.png)

**Comment by yuis-ice** [comment]
I've tried with Zhongwen (a one for chinese) and Rikaikun (a one for japanese), the former didn't work but confirmed Rikaikun works nice on the iframed content area: 

<img src="https://user-images.githubusercontent.com/24733624/152537037-9c5e3680-9cdb-4895-9c48-e2b6fdfd49c3.png" width="600" />

Chrome web store: [Rikakun](https://chrome.google.com/webstore/detail/rikaikun/jipdnfibhldikgcjhfnomkfpcebammhp?hl=en)
Github: [melink14/rikaikun: Translate Japanese by hovering over words.](https://github.com/melink14/rikaikun)

(Note that it works on a URL like "192.168.0.123" but not on "localhost") 

Hope this helps

**Comment by wtetsu** [comment]
@yuis-ice 

Please try installing the latest version of [Mouse Dictionary iframe support](https://chrome.google.com/webstore/detail/mouse-dictionary-iframe-s/nigglogmamjbcnljijokibobpcfgmdfn) ([GitHub](https://github.com/wtetsu/mouse-dictionary-iframe))

In my environment, it worked perfectly.

![b](https://user-images.githubusercontent.com/515948/152586383-9d0f147b-7145-49d2-bbca-4c2a1c1c0f9a.gif)

**Comment by yuis-ice** [comment]
Amazing, confirmed. Many thanks to your hard work.
