### ISSUE TITLE
マウスオーバーしてもウィンドウ内に表示されない(ver1.5.9)

### ISSUE THREAD

**Issue by motidaihuku** [wtetsu/mouse-dictionary#69]
いつもありがたく使わせていただいています．
現在ですが，win10・chrome(ver100.0.4896.75)にて，マウスオーバーしてもウィンドウ内に表示されない状態になっております．単語を選択すると従来どおりウィンドウ内に表示されます．firefoxでは正常に動作しておりました．また，先週あたりは正常に動作していたと思います．
ブラウザのキャッシュ削除，当ソフト以外の拡張機能のoff，iframe supportのインストールなどを試しましたが，いずれも改善しませんでした．
申し訳ありませんが，確認お願いいたします．

**Comment by wtetsu** [comment]
ご報告ありがとうございます、1.5.9のリリースにミスがあったようです。
1.5.10を提出したので、これが反映されればなおると思います。
(お急ぎの場合は[ベータ版](https://chrome.google.com/webstore/detail/mouse-dictionarybeta/ehebancbhejilcmjkoaiphmponbmgbeb)を替わりにお使いください)

**Comment by motidaihuku** [comment]
迅速なご対応ありがうございます！
