### ISSUE TITLE
Search Pause Function to view Youtube etc.

### ISSUE THREAD

**Issue by tomo311** [wtetsu/mouse-dictionary#71]
いつも便利に使わせていただいています。
英語の講師をやっていて、生徒全員にMouse Dictionary をオススメしています。

本題ですが、
Youtube動画を視聴の際に、字幕のデータを読み取れて便利なのですが、
字幕はダブルクリック等で選択することができず、マウスカーソルを外すと辞書の表示も別の単語になってしまいます。

この挙動の対処として、ショートカットキーを設定して、特定のキーを押せば一時的に単語の検索をストップさせる機能があれば便利かと考え、コードを少し追加しました。この後プルリクも送らせていただきます。よろしくお願いします。

**Comment by wtetsu** [comment]
ご提案ありがとうございます。

選択できないような文字に対して使うときに可能な操作が制限されるのは確かなのですが、それの解決策として「検索ストップするショートカットキーを実装する」がベストなのかどうかは検討する必要があるので、お待ち下さい。
結局、そういうショートカットキーを導入するしかないという判断になるかもしれませんが、もっと自然な操作や、より汎用的だったり便利な機能で解決できる案が出るかもしれません。

**Comment by tomo311** [comment]
コメントありがとうございます。
承知しました。
