### ISSUE TITLE
Issue + Additional Commentary

### ISSUE THREAD

**Issue by j0lly6udfella** [wtetsu/mouse-dictionary#73]
I'm new to submitting issues, but I really like your extension. However, a few things I have noticed:

- It would be nice if there was a way I could left click on the extension for "options" or "settings".
- After registering (loading) "free dictionary data", upon opening settings, the data is unalterable and irremovable (even after clicking "reset to default") and is, therefore added to subsequent dictionary files loaded.
![image](https://user-images.githubusercontent.com/97859776/164761405-ec25784a-047f-48a2-aa7b-2bb9bd64deaa.png)

- It would also be nice if there was an example TSV, JSON, etc. file embedded into the docs as a reference for custom formatting.
- The loading symbol for registering data glitches.

Thank you! This is the first time I've submitted an Issue for any project on GitHub. Tell me if I'm missing anything.

**Comment by wtetsu** [comment]
> After registering (loading) "free dictionary data", upon opening settings, the data is unalterable and irremovable (even after clicking "reset to default") and is, therefore added to subsequent dictionary files loaded.

Unfortunately, data deletion feature is not supported due to some technical testriction (#51)

> It would also be nice if there was an example TSV, JSON, etc. file embedded into the docs as a reference for custom formatting.

That's true. [I wrote it.](https://github.com/wtetsu/mouse-dictionary/wiki/Create-your-own-dictionary-data)



> It would be nice if there was a way I could left click on the extension for "options" or "settings".
> The loading symbol for registering data glitches.

What do these mean?

**Comment by wtetsu** [comment]
close due to no response.
