### ISSUE TITLE
Can we manually add words?

### ISSUE THREAD

**Issue by hiramoto** [wtetsu/mouse-dictionary#76]
I would like to add words when I cannot find the word. Would that be possible?

**Comment by wtetsu** [comment]
Doesn't this work?
https://github.com/wtetsu/mouse-dictionary/wiki/Create-your-own-dictionary-data

**Comment by hiramoto** [comment]
It does work. But I want to register the word when it is not in the dictionary without creating a file to import. I really like this extension and it will be far more useful with this function, I suppose.

**Comment by wtetsu** [comment]
For the moment, Mouse Dictionary doesn't support dictionary data editor and has no plan to implement it.
I know it may be useful, but dictionary data is too large to there is no way to sync the data to online storage, so is hard to share across accounts and PC. After editing dictionary data directly, you lose all the data if the PC broke down.
Thus, recommendation is edit plain text file and import it and use it as backup and sharing.

**Comment by hiramoto** [comment]
Sorry for the late reply.
I understand the reason behind it. I would manage somehow with other tools.

**Comment by wtetsu** [comment]
https://github.com/wtetsu/mouse-dictionary/wiki/FAQ
