### ISSUE TITLE
Voice pronunciation went wrong

### ISSUE THREAD

**Issue by chobi2000** [wtetsu/mouse-dictionary#79]
Mouse Dictionaryのスピーカーアイコンを押すと単語の発音を発声してくれる機能がありますが、あるときからこの音声がとても早口で掠れたようなささやき声になってしまいました。
環境はMacOS 13.1  ブラウザはGoogle Chrome およびMicrosoft Edgeですがどちらのブラウザでも同じ現象が起きます。
本機能にはWeb Speech APIを利用しているとの説明を読みましたが、どちらのブラウザもページ読み上げ機能を利用した場合、特に問題なく普通の声で読み上げてくれます。

**Comment by wtetsu** [comment]
私の環境ではとくに異常ありませんでした (maxOS 12.6, Chrome 108.0.5359.124, Windowsでも問題なし)
より詳しく、発生する条件・しない条件をご提示いただければ幸いです。

**Comment by chobi2000** [comment]
macOS 13.1  
Microsoft Edge(バージョン 108.0.1462.54 (公式ビルド) (arm64))
Google Chrome (バージョン: 108.0.5359.124（Official Build）(arm64))

の環境下で特に発生条件はなく、常に変な音声で再生されます。
再生音の事例を動画にとりましたのでご覧ください。

https://user-images.githubusercontent.com/51715450/210169949-ca0c433d-5c72-4c42-9d2b-5e890b91fb8d.mov
https://user-images.githubusercontent.com/51715450/210169952-8fac5324-1529-4d83-95db-f27a82c175b8.mov

**Comment by wtetsu** [comment]
Q1: 手元にmacOS 13.1がないため実際に試すことができないのですが、
この現象が発生したのはmacOS 13.1にしたタイミングでしょうか。

----

Q2: ChromeまたはEdgeで以下のJavaScriptを直接実行した場合、音声は正常でしょうか。
(方法は"Chrome コンソール JavaScript 実行"などで検索してください)

(1)
```js
let s = new SpeechSynthesisUtterance("recently");
speechSynthesis.speak(s);
```

(2)
```js
let s = new SpeechSynthesisUtterance("recently");
s.lang = "en-US";
speechSynthesis.speak(s);
```

(3)
```js
let s = new SpeechSynthesisUtterance("recently");
s.lang = "en";
speechSynthesis.speak(s);
```js

**Comment by chobi2000** [comment]
A1:  発生するようになったタイミングは記憶が定かではありませんが、結構前から発生していたため、MacOS Montley(12.x)時代には既にこうなっていたような気がします。

A2: Javascriptをそれぞれコンソールにて実行してみました。ChromeもEdgeも同じ結果で、
(1)は日本語でrecentlyを発声した感じ（"リーセントリー"  音声は女性）、
(2), (3)についてはMouse Dictionaryで発生しているしているのと同様の早口で掠れた小声の音（音声は男性）になりました。

**Comment by wtetsu** [comment]
他の拡張等が影響している可能性はないでしょうか。
たとえば、Chromeをシークレットモードにして同じスクリプトを実行しても、同じ結果になるでしょうか。

**Comment by chobi2000** [comment]
機能拡張を全てオフにする、プライベートウィンドウで実施する、chromeを-disable-extensionsオプションで起動する等の環境で、それぞれJavaScriptをコンソールから実行してみましたが、残念ながら結果は一緒でした。

**Comment by wtetsu** [comment]
以下3パターンではどうなるでしょうか。

1
```js
let s = new SpeechSynthesisUtterance("recently");
s.lang = "en-US";
s.rate = 1.5;
speechSynthesis.speak(s);
```

2
```js
let s = new SpeechSynthesisUtterance("recently");
s.lang = "en-US";
s.pitch = 0.5;
speechSynthesis.speak(s);
```

3
```js
let s = new SpeechSynthesisUtterance("recently");
s.lang = "en-US";
s.rate = 1.0;
s.pitch = 1.0;
speechSynthesis.speak(s);
```

**Comment by wtetsu** [comment]
以下3パターンではどうなるでしょうか。

1
```js
let s = new SpeechSynthesisUtterance("recently");
s.lang = "en-US";
s.rate = 1.0;
speechSynthesis.speak(s);
```

2
```js
let s = new SpeechSynthesisUtterance("recently");
s.lang = "en-US";
s.pitch = 1.0;
speechSynthesis.speak(s);
```

3
```js
let s = new SpeechSynthesisUtterance("recently");
s.lang = "en-US";
s.rate = 1.0;
s.pitch = 1.0;
speechSynthesis.speak(s);
```

**Comment by chobi2000** [comment]
Edge, Chrome両方で試してみましたが1〜3全て例の掠れて早口の小声の男性の声で発声されます。

**Comment by wtetsu** [comment]
残念ながら再現環境がないため、これ以上の調査は出来なさそうです。
この現象の、より詳しい発生条件の情報をお待ちしています。

**Comment by chobi2000** [comment]
新年早々、お付き合い頂きましてまことにありがとうございました。何か参考になる情報がわかればご報告します。

**Comment by wtetsu** [comment]
この現象はMouse Dictionaryと関係ないと思われるので閉じます。
