### ISSUE TITLE
Is there a way to install two instances of the extension?

### ISSUE THREAD

**Issue by yuis-ice** [wtetsu/mouse-dictionary#80]
I have a two set of a very big dictionary data, and I wish to see one of them in the window at one time. 

But the problem is that when you install two mouse-dictionary on your chrome, they share the same dictionary data.

Is there a way to workaround this issue? Thanks.

**Comment by wtetsu** [comment]
One workaround is to install [Beta version](https://chrome.google.com/webstore/detail/mouse-dictionarybeta/ehebancbhejilcmjkoaiphmponbmgbeb) and import another data.

Note that there is no guarantee that the beta version will be maintained properly. This is just a workaround.
