### ISSUE TITLE
combine with mpv ? 

### ISSUE THREAD

**Issue by omaru-ok** [wtetsu/mouse-dictionary#81]
is it possible to combine this with [mpv](mpv.io)
so we see subtitle  , ?  dictionary? 

mpv is a media player 
that is mostly used by all terminal lover or linux gurus

**Comment by wtetsu** [comment]
What does 'mpv' mean?
Please make your post more readable.

**Comment by omaru-ok** [comment]
@wtetsu sorry if its wasn't understandable , at first , here is fixed ,

**Comment by wtetsu** [comment]
I don't know mpv, but probably it's impossible to use Mouse Dictionary if it doesn't have Web UI.

**Comment by omaru-ok** [comment]
okay , 
i understand
thanks
