### ISSUE TITLE
Can you make your pop up dictionary as a server JS so that I put the JS in my webpage and the visitors will use it without installing?

### ISSUE THREAD

**Issue by bk111** [wtetsu/mouse-dictionary#83]
Can you make your pop up dictionary as a server JS so that I put the JS in my webpage and the visitors will use it without installing?

thanks

**Comment by wtetsu** [comment]
Unfortunately, Mouse Dictionary is designed for client-side use and isn't intended to run server-side. I hope this clarifies your question.
