### ISSUE TITLE
Dynamically position the window near the mouse

### ISSUE THREAD

**Issue by whtsht** [wtetsu/mouse-dictionary#86]
新機能の提案です。マウスの近くにウィンドウが自動的に移動すれば、視線の移動が最小限になり、より便利になると思います。

HTMLテンプレートで出来るかどうか試しましたが、scriptタグが埋め込めないので無理そうです。そのため新機能として導入したいと考えています。

**Comment by wtetsu** [comment]
「私がマウスカーソルの近くに表示されるタイプの辞書UIが嫌い」
というのがMouse Dictionaryの開発動機のひとつなので、
その機能が追加される可能性は残念ながら低いです。

また、

・マウスカーソルの近くといってもどこなのか。下？右？ブラウザからはみだす場合はどうする？
・ウィンドウはいつ表示になっていつ非表示になるのか
・辞書ウィンドウのリサイズはどうやるのか

など考慮すべきことがいろいろあり、
実用的なものにするには現在の設計に単純にマウスの近くに移動する機能を追加して終わり、というわけにはいかず、
いろいろな動作確認・検討を重ねた上で実装する必要があります。

このような私が使わないような機能を維持管理することは、とても大きなコストとして永続的にしかかってくるので、
残念ながら対応することはできないと思います。

**Comment by whtsht** [comment]
@wtetsu 対応ありがとうございます。追加するつもりがない旨、理解しました。

この拡張機能は速度が速いところが気に入っているので、これからも自分で機能を拡張しなが使わせていただきます。

https://github.com/wtetsu/mouse-dictionary/assets/85547207/f227d023-9577-4725-9348-256e0ceb4130
