### ISSUE TITLE
Readability is significantly reduced when the Mouse Dictionary is used with Dark Reader.

### ISSUE THREAD

**Issue by Tirimen0** [wtetsu/mouse-dictionary#87]
こんにちは
Mouse Dictionaryを使用して英文を読みたいと思い導入しようとしたのですが、拡張機能Dark Readerを導入した環境で共存させようとするとどうも著しく可読性が落ちてしまうようです。
Dark Readerをオフにした状態だと正常に動作することを確認しました。
オフにして使えばいい話なのですがどうしてもウェブブラウジングをするときに必須のツールなので、お手すきの際に、確認をお願いします。

Windows 11 
Firefox 121.0 
Mouse Dictionary 1.5.13
Dark Reader 4.9.73
https://addons.mozilla.org/ja/firefox/addon/darkreader/

**Comment by wtetsu** [comment]
オプションから背景色や文字色が設定できるので、そちらで調整してみてください。

**Comment by wtetsu** [comment]
私が少し試した限りでは、この`all:initial;`を消したらそれっぽくなるようでした。

![image](https://github.com/wtetsu/mouse-dictionary/assets/515948/cda22986-fff4-4cde-92eb-1a976bd45363)


![image](https://github.com/wtetsu/mouse-dictionary/assets/515948/f04015b6-4fbf-4f18-90d2-440f339543ab)

**Comment by wtetsu** [comment]
[v1.6.7](https://github.com/wtetsu/mouse-dictionary/releases/tag/v1.6.7)

**Comment by wtetsu** [comment]
1.7.0以降でDark Readerが効かなくなったという方へ:

上級設定にあるDOM種別を「Light DOM」にしてください。

https://github.com/wtetsu/mouse-dictionary/wiki/DOM-Type
