### ISSUE TITLE
Upload custom dictionary file does not seem to work

### ISSUE THREAD

**Issue by carbonmetrics** [wtetsu/mouse-dictionary#89]
I would like to upload a tsv file with my own words. 
However, when I select "Choose file" nothing happens. 
What am I doing wrong here? 

![Screenshot 2024-03-20 at 11 32 09](https://github.com/wtetsu/mouse-dictionary/assets/40055991/d419abdd-1cce-4da4-8bd1-a7b03f3e03c3)

**Comment by wtetsu** [comment]
For me it worked.

![](https://github.com/wtetsu/mouse-dictionary/assets/515948/7cb67d41-2cc3-4bd9-95b7-ae96d453d682)

Would you please restart your browser and try again?

**Comment by carbonmetrics** [comment]
Thanks! For me it doesn't work, but I can drag and drop files on top of the button and click "Load" - the message is that words are imported. 
But then, when I select the relevant words, there is no result.

**Comment by wtetsu** [comment]
Would you please attach the file you imported?

**Comment by carbonmetrics** [comment]
[test.json](https://github.com/wtetsu/mouse-dictionary/files/14665199/test.json)

here it is!

**Comment by wtetsu** [comment]
Worked
![image](https://github.com/wtetsu/mouse-dictionary/assets/515948/8a67d657-7d4e-4d45-9e54-bc23fbc978c8)

**Comment by carbonmetrics** [comment]
"word" is any dictionary, but "For Loop" isn't:

![Screenshot 2024-03-20 at 14 59 57](https://github.com/wtetsu/mouse-dictionary/assets/40055991/0450894c-a1e7-477f-9230-2fa196bb4d88)

**Comment by wtetsu** [comment]
It's not Mouse Dictionary's UI...

**Comment by wtetsu** [comment]
Please read https://github.com/wtetsu/mouse-dictionary/wiki/Getting-started
