### ISSUE TITLE
Unable to launch Mouse Dictionary window from default PDF viewer on latest Chrome & Edge

### ISSUE THREAD

**Issue by kei-mag** [wtetsu/mouse-dictionary#90]
When I click the icon of this extension or push Alt+Z (This is my Keyboard shortcut for launching mouse dictionary), nothing occurred.
But still usable by launching mouse dictionary's PDF viewer and opening target PDF.
---
OS: Windows11 Education 64bit version.23H2 build.22631.3527
Chrome: 64bit ver.124.0.6367.208
Microsoft Edge: 64bit ver.124.0.2478.97
![スクリーンショット 2024-05-15 110703](https://github.com/wtetsu/mouse-dictionary/assets/61485115/58c888ff-d0a4-4cc9-8bcb-fe0d4d22962b)
![スクリーンショット 2024-05-15 110615](https://github.com/wtetsu/mouse-dictionary/assets/61485115/7889e43c-d1fb-4a60-b25f-96640214c34d)
![スクリーンショット 2024-05-15 110549](https://github.com/wtetsu/mouse-dictionary/assets/61485115/e9155703-ef2a-42b9-9e80-28011b047593)

**Comment by wtetsu** [comment]
Has this been the case from the beginning?
Or did it work before and then suddenly stop working one day?

**Comment by kei-mag** [comment]
I'm sorry, this issue was because of my misunderstanding.
I used Google Drive PDF viewer, but I misunderstand that I was using Chrome default PDF viewer.
Mouse dictionary is working well on default PDF viewer on latest Chrome.

Still unable to launch mouse dictionary on Edge after Edge's default PDF viewer changed to Acrobat-based viewer from PDF.js.
I understand that using this extension on Edge is out of support, but will you fix this problem?

**Comment by wtetsu** [comment]
Could you please clarify what you mean by “cannot launch”?
At least in my environment, I can “launch” the Mouse Dictionary on Edge (124.0.2478.105 ) as expected.

**Comment by wtetsu** [comment]
![abc](https://github.com/wtetsu/mouse-dictionary/assets/515948/4260178b-1876-4645-8400-5aee7e9058ab)

**Comment by wtetsu** [comment]
> after Edge's default PDF viewer changed to Acrobat-based viewer

Ah, do you mean **you** changed the Edge's PDF viewer?
(I don't know that settings)
If so, probably Mouse Dictionary cannot support that environment.

**Comment by kei-mag** [comment]
I apologize for this late reply.
After reinstalling Microsoft Edge on my computer, mouse dictionary worked well like what you showed.
This issue seemed to be caused by my computer problem (my edge opened new tab very slowly before reinstalling it).
Thank you for your quickly support and great work.
